apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "word-service.fullname" . }}
  labels:
    {{- include "word-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "word-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "word-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "word-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "word-service.fullname" . }}-config
                  key: database_dialect
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "word-service.fullname" . }}-config
                  key: database_name
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "word-service.fullname" . }}-config
                  key: database_username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.config.database_password.secretName}}
                  key: {{.Values.config.database_password.secretKey}}
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "word-service.fullname" . }}-config
                  key: database_port
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "word-service.fullname" . }}-config
                  key: database_host
            - name: METRIC_EXPORTER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "word-service.fullname" . }}-config
                  key: metric_exporter_url
            - name: METRIC_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "word-service.fullname" . }}-config
                  key: metric_interval
            - name: TRACE_EXPORTER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "word-service.fullname" . }}-config
                  key: trace_exporter_url
            - name: LOG_EXPORTER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "word-service.fullname" . }}-config
                  key: log_exporter_url
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "word-service.fullname" . }}-config
                  key: service_name
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
