Vagrant.configure("2") do |config|
  # Configure provider
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.memory = 8192
    libvirt.cpus = 4
  end

  config.vm.box = "debian/bullseye64"
  # Default timeout (300 sec) is a little short for the VM to start
  config.vm.boot_timeout = 600
  # Disable NFS file sharing between host and VM
  config.vm.synced_folder ".", "/vagrant", disabled: true

  MASTER_IP = "192.168.10.10"

  # Master VM
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: MASTER_IP

    # Setup k3s cluster with Ansible
    master.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../ansible/setup-kube-cluster/playbook.yaml"
      # Run playbook all VMs in one run
      ansible.limit = "all"
      ansible.groups = {
        "master" => ["master"],
        "node" => ["node-[1:#{NODES}]"],
        "all:vars" => {
          "master_ip" => MASTER_IP,
          "aditional_k3s_args" => ""
        }
      }
    end
  end

  NODES = 3

  # Node VMs
  (1..NODES).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"
      node.vm.network "private_network", ip: "192.168.10.1#{i}"
    end
  end
end
