ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-issuer"
  hosts:
    - host: www.preprod.gitops-demo.a-gomez.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: frontend-tls
      hosts:
        - www.preprod.gitops-demo.a-gomez.fr
