grafana:
  additionalDataSources:
    - name: Jaeger
      uid: webstore-traces
      type: jaeger
      url: http://jaeger-query:16686/jaeger/ui
      editable: true
      isDefault: false
    - name: Loki
      uid: webstore-logs
      type: loki
      url: http://loki:3100
      editable: true
      isDefault: false

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: Istio
          orgId: 1
          folder: "Istio"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/istio

  dashboards:
    istio:
      istio-mesh-dashboard:
        gnetId: 7639
        revision: 166
        datasource: Prometheus
      istio-service-dashboard:
        gnetId: 7636
        revision: 166
        datasource: Prometheus
      istio-workload-dashboard:
        gnetId: 7630
        revision: 166
        datasource: Prometheus
      istio-performance-dashboard:
        gnetId: 11829
        revision: 166
        datasource: Prometheus
      istio-controlplane-dashboard:
        gnetId: 7645
        revision: 166
        datasource: Prometheus
