{{- if .Values.clusterIssuers.letsencrypt.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    # The ACME server URL
    server: {{ if .Values.clusterIssuers.letsencrypt.staging }} https://acme-staging-v02.api.letsencrypt.org/directory {{ else }} https://acme-v02.api.letsencrypt.org/directory {{ end }}
    # Email address used for ACME registration
    email: {{ .Values.clusterIssuers.letsencrypt.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-issuer-key
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end }}
