resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-issuer"
  hosts:
    - host: word.preprod.192.168.10.10.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: word-tls
      hosts:
        - word.preprod.192.168.10.10.sslip.io
