ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-issuer'
  hosts:
    - host: word.preprod.gitops-demo.a-gomez.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: word-tls
      hosts:
        - word.preprod.gitops-demo.a-gomez.fr
