resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-issuer'
  hosts:
    - host: word.gitops-demo.a-gomez.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: word-tls
      hosts:
        - word.gitops-demo.a-gomez.fr
