apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: main
spec:
  mode: deployment
  config: |
    receivers:
        otlp:
            protocols:
                grpc:
                http:
                    cors:
                        allowed_origins:
                            - "http://*"
                            - "https://*"

    exporters:
        otlp:
            endpoint: {{.Values.collectors.main.otlpEndpoint | quote}}
            tls:
                insecure: true
        loki:
            endpoint: {{.Values.collectors.main.lokiEndpoint | quote}}
        logging:
        prometheus:
            endpoint: {{.Values.collectors.main.prometheusEndpoint | quote}}
            resource_to_telemetry_conversion:
                enabled: true
            enable_open_metrics: true

    processors:
        batch:
        attributes:
            actions:
                - action: insert
                  key: loki.attribute.labels
                  value: event.domain

        resource:
            attributes:
                - action: insert
                  key: loki.resource.labels
                  value: service.name

    service:
        pipelines:
            traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlp, logging]
            metrics:
                receivers: [otlp]
                processors: [batch]
                exporters: [prometheus, logging]
            logs:
                receivers: [otlp]
                processors: [batch, attributes, resource]
                exporters: [loki, logging]
