{{- range $k, $v := .Values.collectors }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $k }}-collector-metrics
  labels:
    monitoring: otel-collectors
    release: {{$.Values.prometheusOperator.releaseName}}
spec:
  jobLabel: otel-collectors
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $k }}-collector-monitoring
  namespaceSelector:
    matchNames:
      - {{$.Release.Namespace}}
  endpoints:
  - port: monitoring
{{ end -}}
